name: IntegrationContinue

jobs:
  uv-example:
    name: python

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Run precommit uv
        run: uv run pre-commit run -a

      - name: Run pytest
        run: uv run python -m unittest

    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
